//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/ProxySOAP")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IProxy")]
    public interface IProxy {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxy/getStation", ReplyAction="http://tempuri.org/IProxy/getStationResponse")]
        string getStation(int number, string chosenContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxy/getStation", ReplyAction="http://tempuri.org/IProxy/getStationResponse")]
        System.Threading.Tasks.Task<string> getStationAsync(int number, string chosenContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxy/getContracts", ReplyAction="http://tempuri.org/IProxy/getContractsResponse")]
        string getContracts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxy/getContracts", ReplyAction="http://tempuri.org/IProxy/getContractsResponse")]
        System.Threading.Tasks.Task<string> getContractsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxy/getAllStationsOfAContract", ReplyAction="http://tempuri.org/IProxy/getAllStationsOfAContractResponse")]
        string getAllStationsOfAContract(string chosenContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxy/getAllStationsOfAContract", ReplyAction="http://tempuri.org/IProxy/getAllStationsOfAContractResponse")]
        System.Threading.Tasks.Task<string> getAllStationsOfAContractAsync(string chosenContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxy/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IProxy/GetDataUsingDataContractResponse")]
        WcfServiceLibrary1.ServiceReference1.CompositeType GetDataUsingDataContract(WcfServiceLibrary1.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxy/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IProxy/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WcfServiceLibrary1.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(WcfServiceLibrary1.ServiceReference1.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProxyChannel : WcfServiceLibrary1.ServiceReference1.IProxy, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProxyClient : System.ServiceModel.ClientBase<WcfServiceLibrary1.ServiceReference1.IProxy>, WcfServiceLibrary1.ServiceReference1.IProxy {
        
        public ProxyClient() {
        }
        
        public ProxyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProxyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getStation(int number, string chosenContract) {
            return base.Channel.getStation(number, chosenContract);
        }
        
        public System.Threading.Tasks.Task<string> getStationAsync(int number, string chosenContract) {
            return base.Channel.getStationAsync(number, chosenContract);
        }
        
        public string getContracts() {
            return base.Channel.getContracts();
        }
        
        public System.Threading.Tasks.Task<string> getContractsAsync() {
            return base.Channel.getContractsAsync();
        }
        
        public string getAllStationsOfAContract(string chosenContract) {
            return base.Channel.getAllStationsOfAContract(chosenContract);
        }
        
        public System.Threading.Tasks.Task<string> getAllStationsOfAContractAsync(string chosenContract) {
            return base.Channel.getAllStationsOfAContractAsync(chosenContract);
        }
        
        public WcfServiceLibrary1.ServiceReference1.CompositeType GetDataUsingDataContract(WcfServiceLibrary1.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<WcfServiceLibrary1.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(WcfServiceLibrary1.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
